location / {
    try_files $uri $uri/ /index.html;
    include include.d/nocache.conf;
}

location /static {
   alias /var/www/public/static/;
   include include.d/allcache.conf;
}

location /manifest.json {
    proxy_pass http://backend:3000/manifest.json;
    proxy_connect_timeout 10s;
    proxy_send_timeout    60s;
    proxy_read_timeout    60s;
    proxy_next_upstream   error timeout http_502 http_503 http_504;
    proxy_next_upstream_tries 3;
}

location /socket.io/ {
    proxy_pass http://backend:3000;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
    proxy_connect_timeout 10s;
    proxy_send_timeout    60s;
    proxy_read_timeout    60s;
}

location /backend/public/ {
    add_header Content-Disposition 'attachment';
    alias /var/www/backend-public/;
    include include.d/allcache.conf;
}

location /backend/ {
    rewrite ^/backend/(.*) /$1 break;
    proxy_pass http://backend:3000;
    proxy_connect_timeout 10s;
    proxy_send_timeout    60s;
    proxy_read_timeout    60s;
    proxy_next_upstream   error timeout http_502 http_503 http_504;
    proxy_next_upstream_tries 3;
}

include ticketz.d/*.conf;

include "include.d/spa.conf";
